library(datasets)
data(iris)
summary(iris)
summary(iris$Sepal.Length)
names(iris)
tolower(names(iris))
install.packages("dplyr")
library(dplyr)
virginica <- filter(iris, Species == "virginica")
head(virginica)
sepalLength6 <- filter(iris, Species == "virginica", Sepal.Length >6)
tail(sepalLength6)
selected <- select(iris, Sepal.Length, Sepal.Width, Petal.Length)
selected2 <- select(iris, Sepal.Length:Petal.Length)
head(selected2, 3)
identical(selected, selected2)
newCol <- mutate(iris, greater.half = Sepal.Width > 0.5* Sepal.Length)
tail(newCol)
sum(newCol$greater.half, TRUE)
newCol <- arrange(newCol, petal.width)
head(newCol)
arr.virg <- newCol %>% filter(Species == "virginica") %>% arrange(Sepal.Width)
arr.virg[30:35,]
summarise(arr.virg, Mean.Length = mean(Sepal.Length, na.rm = TRUE))
summarize(iris, sd(iris$Sepal.Length))
plot(iris)
plot(iris$Sepal.Width, iris$Sepal.Length)
hist(iris$Sepal.Width)
